# Generated by Django 5.2.5 on 2025-11-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_cliente',
            field=models.CharField(choices=[('natural', 'Persona Natural'), ('empresa', 'Empresa'), ('admin', 'Administrador'), ('atencion_cliente', 'Atención al Cliente')], default='natural', max_length=20),
        ),
    ]
