# Generated by Django 5.2.5 on 2025-11-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('organicos', 'Orgánicos'), ('harinas', 'Harinas'), ('sin gluten', 'Sin Gluten'), ('s/lacteos', 'Sin Lácteos'), ('bebidas', 'Bebidas'), ('snacks', 'Snacks'), ('suplementos', 'Suplementos'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
