# Generated by Django 5.2.6 on 2025-11-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado (simulado)'), ('en proceso', 'En proceso'), ('en camino', 'En camino'), ('entregado', 'Entregado'), ('modificado', 'Modificado')], default='pendiente', max_length=20),
        ),
    ]
